language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libogg-dev
      - libopus-dev

env: PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/opt/openssl/lib/pkgconfig

install: if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew bundle; fi

script:
  - ./autogen.sh
  - ./configure
  - make
  - make distcheck
