language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

osx_image: xcode11.3

addons:
  apt:
    packages:
      - doxygen
      - libogg-dev
      - libopus-dev
      - libssl-dev
  homebrew:
    brewfile: true

env: PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/opt/openssl/lib/pkgconfig

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      curl -O https://cmake.org/files/v3.16/cmake-3.16.9-Linux-x86_64.tar.gz;
      tar xzf cmake-3.16.9-Linux-x86_64.tar.gz;
      export PATH="${PWD}/cmake-3.16.9-Linux-x86_64/bin:${PATH}";
    fi

script:
  - cmake -Bbuild -H.
  - cmake --build build
  - ./autogen.sh
  - ./configure
  - make
  - make distcheck
